FROM python

WORKDIR /app

COPY . /app

CMD ["python", "rng.py"]

# COMMANDS
# docker run -it image_id (runs python script so user can enter input into container via terminal)
# docker start -ai container_id (to rerun the container with -a for attached mode and -i for input)