# Shortcut ctrl + space to see available tags
FROM python:3.7

WORKDIR /app

COPY . .

CMD ["python", "bmi.py"]

# CREATE python-app IMAGE (cd into folder first)
# docker build -t bmi-app:v1 .

# CREATE CONTAINER (don't need to cd into folder first)
# docker run -it --name mypythonapp --rm bim-app:v1 
# docker stop mypythonapp
# docker start -i -a pythonapp (to restart container, but only if you haven't done --rm)






